steps:
  integrationArtifactDeploy:
    cpiApiServiceKeyCredentialsId: techedServiceKeyCred
    integrationFlowId: P2011721593-flow4
  integrationArtifactGetMplStatus:
    cpiApiServiceKeyCredentialsId: techedServiceKeyCred
    integrationFlowId: P2011721593-flow4
  integrationArtifactUpload:
    cpiApiServiceKeyCredentialsId: techedServiceKeyCred
    integrationFlowId: P2011721593-flow4
    integrationFlowName: P2011721593-flow4
    packageId: CICD
    filePath: P2011721593-flow4.zip